In [1]:
import numpy as np

In [8]:
my_arr = np.arange(1_000_000)  # como ndarray
my_list = list(range(1_000_000))  # como lista

In [9]:
type(my_arr), type(my_list)

(numpy.ndarray, list)

In [10]:
%timeit my_arr2 = my_arr * 2

1.6 ms ± 43.9 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [11]:
%timeit my_list2 = [x * 2 for x in my_list]

71.3 ms ± 879 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [13]:
# NumPy enables batch computations with similar syntax to scalar values on built-in Python objects
data = np.array([[-2, 0.34, 3.24], [0.5, 2.4, 3.6]])
data

array([[-2.  ,  0.34,  3.24],
       [ 0.5 ,  2.4 ,  3.6 ]])

In [14]:
data * 10

array([[-20. ,   3.4,  32.4],
       [  5. ,  24. ,  36. ]])

In [15]:
data + 3.5 * data

array([[-9.  ,  1.53, 14.58],
       [ 2.25, 10.8 , 16.2 ]])

In [18]:
data.shape, data.dtype

((2, 3), dtype('float64'))

The easiest way to create an array is to use the array function. This accepts any sequence-like object

In [19]:
data = [1, 2.5, 3.7, 9.14]
arr_1 = np.array(data)
arr_1

array([1.  , 2.5 , 3.7 , 9.14])

In [21]:
arr_1.shape

(4,)

In [23]:
# Nested sequences, will be converted into a multidimensional array:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr_2 = np.array(data2)
arr_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
arr_2.ndim, arr_2.shape

(2, (2, 4))

Otras formas de crear un ndarray:
* zeros
* ones
* empty (reserva el espacio, pero no lo inicializa)

In [27]:
np.ones((2, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
np.zeros((4, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

Otras formas:
* array
* asarray
* arange
* ones, ones_like  (like es para que tenga la misma shape que el indicado)
* zeros, zeros_like
* full, full_like
* empty, empty_like
* eye, identity

El dtype se busca automáticamente, aunque también es posible indicarlo en la creación
* int8(16, 32, 64), uint8(16, 32, 649
* float16(32, 64, 128)
* complex64(128, 256)
* bool
* object
* string_
* unicode_

In [30]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [32]:
float_arr = arr.astype('float64')
float_arr.dtype

dtype('float64')

## Arithmetic with NumPy Arrays

In [33]:
arr_i = np.array([[1, 2, 3], [4, 5, 6]])
arr_i

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
arr_i.dtype

dtype('int32')

In [35]:
arr_f = arr_i.astype('float')
arr_f

array([[1., 2., 3.],
       [4., 5., 6.]])

In [36]:
arr_f.dtype

dtype('float64')

## Vectorización de operaciones

In [39]:
arr_f * arr_f

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [38]:
arr_f ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [40]:
# Arithmetic operations with scalars propagate the scalar argument to each element in the array:
1 / arr_f

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [41]:
# Comparisons between arrays of the same size yield boolean arrays
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr_f <= arr2

array([[False,  True, False],
       [ True, False,  True]])

## Basic Indexing and Slicing

In [44]:
arr_1 = np.arange(10)
arr_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arr_1[5]

5

In [46]:
arr_1[5:8]

array([5, 6, 7])

In [47]:
arr_1[6:]

array([6, 7, 8, 9])

In [48]:
arr_1[:4] = 14.2
arr_1

array([14, 14, 14, 14,  4,  5,  6,  7,  8,  9])

In [49]:
# Observar que como el dypte es int, pues en vez de valer 14.2 valen 14

#### An important first distinction from Python's built-in lists is that array slices are **views** on the original array.
This means that the data is not copied, and any modifications to the view will be reflected in the source array.

In [58]:
# Ejemplo
# array no es un nuevo objeto, es solo un view de arr_1
arr_slice = arr_1[:4]

In [59]:
# Así, al modificar array, también estamos modificando arr_1
arr_slice[2] = 17
arr_1

array([14, 14, 17, 14,  4,  5,  6,  7,  8,  9])

In [60]:
arr_slice[:] = 64
arr_1

array([64, 64, 64, 64,  4,  5,  6,  7,  8,  9])

## higher dimensional arrays

In [61]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
# In a two-dimensional array, the elements at each index are no longer scalars but rather one-dimensional arrays:
arr2d[1]   # No es un escalar, sino un vecotr (1-dim array)

array([4, 5, 6])

In [64]:
# si queremos el elemento, habrá que seguir indexando...
arr2d[1][1]

5

In [66]:
# Axis 0 --> indica la fila
# Axis 1 --> la columna
arr2d[2][1]  # la última fila, la segunda columna

8

In multidimensional arrays, if you omit later indices, the returned object will be a lower dimensional ndarray consisting of all the data along the higher dimensions. So in the 2 × 2 × 3 array arr3d:

In [67]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [68]:
arr3d[0]  

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
arr3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [70]:
arr3d[0][1]

array([4, 5, 6])

In [71]:
# Aquí sería Axis 0 --> capa  (del frente hacia atrás)
# Axis 1 pues la fila
# Axis 2 la columna

In [72]:
# Both scalar values and arrays can be assigned to arr3d[0]:
old_values = arr3d[0].copy()
# Es un nuevo objeto, pq usamos el método copy
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
arr3d[0] = 42  # Hace broadcast y coloca en todos los elementos un 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [75]:
# Volvemos a dejarlo como estaba para hacer otra prueba
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [76]:
arr3d[1][0]

array([7, 8, 9])

In [77]:
arr3d[1, 0]

array([7, 8, 9])

## más de slicing

In [78]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
arr2d[:2, 1:]  # doble slicing... la primera rebanada es en el eje 0 (fila) y la segunda para l acolumna

array([[2, 3],
       [5, 6]])

In [82]:
arr2d[1, :2]  # coger la segunda fila, y las dos primeras columnas

array([4, 5])

In [84]:
# Note that a colon by itself means to take the entire axis, so you can slice only higher dimensional axes by doing:
arr2d[:, :1]  # cogemos todas las filas, pero sólo la segunda columna...

array([[1],
       [4],
       [7]])

In [85]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])