In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1_000_000)  # como ndarray
my_list = list(range(1_000_000))  # como lista

In [3]:
type(my_arr), type(my_list)

(numpy.ndarray, list)

In [4]:
%timeit my_arr2 = my_arr * 2

1.83 ms ± 46.5 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [5]:
%timeit my_list2 = [x * 2 for x in my_list]

79.6 ms ± 863 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [6]:
# NumPy enables batch computations with similar syntax to scalar values on built-in Python objects
data = np.array([[-2, 0.34, 3.24], [0.5, 2.4, 3.6]])
data

array([[-2.  ,  0.34,  3.24],
       [ 0.5 ,  2.4 ,  3.6 ]])

In [7]:
data * 10

array([[-20. ,   3.4,  32.4],
       [  5. ,  24. ,  36. ]])

In [8]:
data + 3.5 * data

array([[-9.  ,  1.53, 14.58],
       [ 2.25, 10.8 , 16.2 ]])

In [9]:
data.shape, data.dtype

((2, 3), dtype('float64'))

The easiest way to create an array is to use the array function. This accepts any sequence-like object

In [10]:
data = [1, 2.5, 3.7, 9.14]
arr_1 = np.array(data)
arr_1

array([1.  , 2.5 , 3.7 , 9.14])

In [11]:
arr_1.shape

(4,)

In [12]:
# Nested sequences, will be converted into a multidimensional array:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr_2 = np.array(data2)
arr_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
arr_2.ndim, arr_2.shape

(2, (2, 4))

Otras formas de crear un ndarray:
* zeros
* ones
* empty (reserva el espacio, pero no lo inicializa)

In [14]:
np.ones((2, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.zeros((4, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

Otras formas:
* array
* asarray
* arange
* ones, ones_like  (like es para que tenga la misma shape que el indicado)
* zeros, zeros_like
* full, full_like
* empty, empty_like
* eye, identity

El dtype se busca automáticamente, aunque también es posible indicarlo en la creación
* int8(16, 32, 64), uint8(16, 32, 649
* float16(32, 64, 128)
* complex64(128, 256)
* bool
* object
* string_
* unicode_

In [16]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [17]:
float_arr = arr.astype('float64')
float_arr.dtype

dtype('float64')

## Arithmetic with NumPy Arrays

In [18]:
arr_i = np.array([[1, 2, 3], [4, 5, 6]])
arr_i

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
arr_i.dtype

dtype('int32')

In [20]:
arr_f = arr_i.astype('float')
arr_f

array([[1., 2., 3.],
       [4., 5., 6.]])

In [21]:
arr_f.dtype

dtype('float64')

## Vectorización de operaciones

In [22]:
arr_f * arr_f

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [23]:
arr_f ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [24]:
# Arithmetic operations with scalars propagate the scalar argument to each element in the array:
1 / arr_f

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [25]:
# Comparisons between arrays of the same size yield boolean arrays
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr_f <= arr2

array([[False,  True, False],
       [ True, False,  True]])

## Basic Indexing and Slicing

In [26]:
arr_1 = np.arange(10)
arr_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr_1[5]

5

In [28]:
arr_1[5:8]

array([5, 6, 7])

In [29]:
arr_1[6:]

array([6, 7, 8, 9])

In [30]:
arr_1[:4] = 14.2
arr_1

array([14, 14, 14, 14,  4,  5,  6,  7,  8,  9])

In [31]:
# Observar que como el dypte es int, pues en vez de valer 14.2 valen 14

#### An important first distinction from Python's built-in lists is that array slices are **views** on the original array.
This means that the data is not copied, and any modifications to the view will be reflected in the source array.

In [32]:
# Ejemplo
# array no es un nuevo objeto, es solo un view de arr_1
arr_slice = arr_1[:4]

In [33]:
# Así, al modificar array, también estamos modificando arr_1
arr_slice[2] = 17
arr_1

array([14, 14, 17, 14,  4,  5,  6,  7,  8,  9])

In [34]:
arr_slice[:] = 64
arr_1

array([64, 64, 64, 64,  4,  5,  6,  7,  8,  9])

## higher dimensional arrays

In [35]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
# In a two-dimensional array, the elements at each index are no longer scalars but rather one-dimensional arrays:
arr2d[1]   # No es un escalar, sino un vecotr (1-dim array)

array([4, 5, 6])

In [37]:
# si queremos el elemento, habrá que seguir indexando...
arr2d[1][1]

5

In [38]:
# Axis 0 --> indica la fila
# Axis 1 --> la columna
arr2d[2][1]  # la última fila, la segunda columna

8

In multidimensional arrays, if you omit later indices, the returned object will be a lower dimensional ndarray consisting of all the data along the higher dimensions. So in the 2 × 2 × 3 array arr3d:

In [39]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [40]:
arr3d[0]  

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
arr3d[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [42]:
arr3d[0][1]

array([4, 5, 6])

In [43]:
# Aquí sería Axis 0 --> capa  (del frente hacia atrás)
# Axis 1 pues la fila
# Axis 2 la columna

In [44]:
# Both scalar values and arrays can be assigned to arr3d[0]:
old_values = arr3d[0].copy()
# Es un nuevo objeto, pq usamos el método copy
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
arr3d[0] = 42  # Hace broadcast y coloca en todos los elementos un 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [46]:
# Volvemos a dejarlo como estaba para hacer otra prueba
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [47]:
arr3d[1][0]

array([7, 8, 9])

In [48]:
arr3d[1, 0]

array([7, 8, 9])

## más de slicing

In [49]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
arr2d[:2, 1:]  # doble slicing... la primera rebanada es en el eje 0 (fila) y la segunda para l acolumna

array([[2, 3],
       [5, 6]])

In [52]:
arr2d[1, :2]  # coger la segunda fila, y las dos primeras columnas

array([4, 5])

In [53]:
# Note that a colon by itself means to take the entire axis, so you can slice only higher dimensional axes by doing:
arr2d[:, :1]  # cogemos todas las filas, pero sólo la segunda columna...

array([[1],
       [4],
       [7]])

In [54]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [68]:
arr2d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr2d = arr2d.reshape((3, 3))
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [71]:
arr2d[2], arr2d[2].shape

(array([7, 8, 9]), (3,))

In [72]:
arr2d[2, :], arr2d[2, :].shape

(array([7, 8, 9]), (3,))

In [74]:
arr2d[2:], arr2d[2:].shape

(array([[7, 8, 9]]), (1, 3))

In [75]:
arr2d[2:, :], arr2d[2:, :].shape

(array([[7, 8, 9]]), (1, 3))

In [77]:
arr2d[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [78]:
arr2d[1, :2], arr2d[1, :2].shape

(array([4, 5]), (2,))

In [79]:
arr2d[1:2, :2], arr2d[1:2, :2].shape

(array([[4, 5]]), (1, 2))

## Boolean indexing

In [110]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7],  # nombre correspondiente es Bob
                 [0, 2],  # nombre correspondiente es Joe
                 [-5, 6],  # nombre correspondiente es Will
                 [0, 0],  # nombre correspondiente es Bob
                 [1, 2],  # nombre correspondiente es Will
                 [-12, -4],  # nombre correspondiente es Joe
                 [3, 4],  # nombre correspondiente es Joe
                ])
print(data)
data.shape

[[  4   7]
 [  0   2]
 [ -5   6]
 [  0   0]
 [  1   2]
 [-12  -4]
 [  3   4]]


(7, 2)

In [83]:
# Cuáles son los elementos de data en los que el name correspondiente es BOb?
data[names == 'Bob']

array([[4, 7],
       [0, 0]])

In [84]:
data[names == "Bob", 1:]

array([[7],
       [0]])

In [85]:
data[names == "Bob", 1]

array([7, 0])

In [86]:
# To select everything but "Bob", you can either use != or negate the condition using ~:
data[names != "Bob"]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [88]:
data[~(names == 'Bob')]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [89]:
# Obs: names == 'Bob' es un vector booleano
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [90]:
# forma 1 de el vector names distinto de Bob
names != 'Bob'


array([False,  True,  True, False,  True,  True,  True])

In [91]:
~(names == 'Bob')

array([False,  True,  True, False,  True,  True,  True])

In [92]:
# Otra forma
condicion = names == 'Bob'
condicion

array([ True, False, False,  True, False, False, False])

In [93]:
~condicion

array([False,  True,  True, False,  True,  True,  True])

In [94]:
data[~condicion]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [96]:
# Mostrar los datos asociados cuando el nombre es Bob o Will
data[ (names=='Bob') | (names=='Will')]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [97]:
# También podíamos haber hecho, poco a poco
# primero hallando la máscara (vector Booleano que nos señala si lo vamos a seleccionar)
mask = (names == 'Bob') | (names=='Will')
data[mask]
                           

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [100]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [111]:
# Vamos a hacer que todos los valores < 0 de data se transformen en 0
data[data < 0] = 0
data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

In [112]:
# You can also set whole rows or columns using a one-dimensional boolean array:
# Hacer que todas las filas distintas de Joe valgan 7
data[names!='Joe'] = 7
data

array([[7, 7],
       [0, 2],
       [7, 7],
       [7, 7],
       [7, 7],
       [0, 0],
       [3, 4]])

## Fancy indexing
Fancy indexing is a term adopted by NumPy to describe indexing using integer arrays
O sea, indexamos usando un array.... 

In [114]:
array = np.zeros((8, 4))
array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [115]:
# Vamos a hacer que cada fila valga un valor del 0 al 7
for i in range(8):
    array[i] = i  # o sea, el vector fila i, que valga, todas sus componentes, i
array

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [116]:
# Vamos a hacer fancy indexing para seleccionar la fila 2 y la 6
array[[2, 6]]

array([[2., 2., 2., 2.],
       [6., 6., 6., 6.]])

In [117]:
# También podemos usar los clásicos índices negativos
array[[0, 3, -1, 2, -3]]

array([[0., 0., 0., 0.],
       [3., 3., 3., 3.],
       [7., 7., 7., 7.],
       [2., 2., 2., 2.],
       [5., 5., 5., 5.]])

Passing multiple index arrays does something slightly different; it selects a one-dimensional array of elements corresponding to each tuple of indices:

In [118]:
array = np.arange(32).reshape(8, 4)
array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [123]:
array[[1, 5, 7, 2], [0, 3, 1, 2]]



array([ 4, 23, 29, 10])

In [125]:
# Here the elements (1, 0), (5, 3), (7, 1), and (2, 2)
# Esto lo que hace es crear un array con los elementos correspondientes
# seleccionando, por orden, la fila y la columna correspondiente... en
# en este caso
print(array[1, 0], array[5, 3], array[7][1], array[2, 2])

4 23 29 10


## Transposing Arrays and Swapping Axes